/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cryptex;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Prasith Lakshan
 */
public class SelectKey_Dialog extends javax.swing.JFrame {

    /**
     * Creates new form SelectKey_Dialog
     */
    public SelectKey_Dialog() {
        initComponents();
        groupButton();
        setVisible(true);
        setLocationRelativeTo(null);
    }

    private void groupButton() {
        ButtonGroup bg1 = new ButtonGroup();
        bg1.add(radioButtonDefaultKey);
        bg1.add(radioButtonCustomKey);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButtonDefaultKey = new javax.swing.JRadioButton();
        encryptButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        radioButtonCustomKey = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jPWField2 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        radioButtonDefaultKey.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        radioButtonDefaultKey.setSelected(true);
        radioButtonDefaultKey.setText("Use default Key to encrypt");
        radioButtonDefaultKey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioButtonDefaultKeyMouseClicked(evt);
            }
        });
        radioButtonDefaultKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonDefaultKeyActionPerformed(evt);
            }
        });

        encryptButton2.setText("Encrypt");
        encryptButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Key: ");
        jLabel2.setEnabled(false);

        jLabel4.setText("<html>Uses the Key you provide for encryption. To decrypt, the Key is required. <br/><i>Make sure you do not forget the key!!</i></html>");
        jLabel4.setEnabled(false);

        jLabel1.setText("<html>Uses a random key generated by the app to encrypt the text. <br/>Can be decrypted by anyone using Cryptex.<br/>But is secure enough for regular uses.  </html>");
        jLabel1.setEnabled(false);

        radioButtonCustomKey.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        radioButtonCustomKey.setText("Let me choose a key");
        radioButtonCustomKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonCustomKeyActionPerformed(evt);
            }
        });

        jLabel3.setText("( 5 Digits only) ");
        jLabel3.setEnabled(false);

        jPWField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPWField2.setEnabled(false);
        jPWField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPWField2FocusLost(evt);
            }
        });
        jPWField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPWField2KeyPressed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPWField2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(encryptButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioButtonCustomKey)
                            .addComponent(radioButtonDefaultKey))))
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(radioButtonDefaultKey)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(radioButtonCustomKey)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jPWField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(encryptButton2)
                            .addComponent(jButton2))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioButtonDefaultKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonDefaultKeyActionPerformed
        jLabel1.setEnabled(true);
        jLabel2.setEnabled(false);
        jLabel3.setEnabled(false);
        jLabel4.setEnabled(false);
        jPWField2.setEnabled(false);
    }//GEN-LAST:event_radioButtonDefaultKeyActionPerformed

    private String val = "0";
    
    private void encryptButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptButton2ActionPerformed
        String key = jPWField2.getText();
        //jLabel5.setText(key);

        if(radioButtonDefaultKey.isSelected()) {
            
            this.dispose();

        }

        if(radioButtonCustomKey.isSelected()) {
            if(key.matches("[0-9]+") && (key.length() == 5) ) {
                //int PW = Integer.parseInt(key);
                
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this, "Invalid Key!\nIt either contains non-numerals or is not 5 digits long.");
            }
        }

    }//GEN-LAST:event_encryptButton2ActionPerformed

    private void radioButtonCustomKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonCustomKeyActionPerformed
        jLabel1.setEnabled(false);
        jLabel2.setEnabled(true);
        jLabel3.setEnabled(true);
        jLabel4.setEnabled(true);
        jPWField2.setEnabled(true);
        //radioButtonDefaultKey.setSelected(false);
    }//GEN-LAST:event_radioButtonCustomKeyActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void radioButtonDefaultKeyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioButtonDefaultKeyMouseClicked
        val = "0";
    }//GEN-LAST:event_radioButtonDefaultKeyMouseClicked

    private void jPWField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPWField2FocusLost
        String temp = jPWField2.getText();
        if(temp.matches("[0-9]+") && (temp.length() == 5) ) {
            val = temp;
        } 
        
    }//GEN-LAST:event_jPWField2FocusLost

    private void jPWField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPWField2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPWField2KeyPressed

    String get() {
        return val;
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectKey_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SelectKey_Dialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
     javax.swing.JButton encryptButton2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPWField2;
    private javax.swing.JRadioButton radioButtonCustomKey;
    private javax.swing.JRadioButton radioButtonDefaultKey;
    // End of variables declaration//GEN-END:variables
}
